### ISSUE TITLE
Feature Request: use only one tab for all the previews

### ISSUE THREAD

**Issue by eidolies** [brainFade/atom-markdown-auto-preview#3]
I'd like to be able to use only one preview tab in a single Atom window, which would be used for all the previews. Instead of opening a new preview pane for each file, opening a file would use the same tab and load the preview inside it. New file tabs would open on the left of the preview so the preview tab sticks to the rightmost border.

Thanks so much for this package, it greatly helps me.

**Comment by Bug-Spray** [comment]
Hi eidolies. Thanks! Glad you like it.

To clarify:
Currently, when a file tab is opened in one pane, the preview is opened (either automatically, or manually) in a second pane to the right.
If a second file is opened, the second preview becomes another tab in the same preview pane as the first.

You would like all previews to be in a single tab?
As if Preview A is closed and Preview B is created when switching from File A to File B?

**Comment by brainFade** [comment]
Hi eidolies. Thanks! Glad you like it.

To clarify:
Currently, when a file tab is opened in one pane, the preview is opened (either automatically, or manually) in a second pane to the right.
If a second file is opened, the second preview becomes another tab in the same preview pane as the first.

You would like all previews to be in a single tab?
As if Preview A is closed and Preview B is created when switching from File A to File B?

**Comment by eidolies** [comment]
Hello!

> You would like all previews to be in a single tab?
> As if Preview A is closed and Preview B is created when switching from File A to File B? 

Exactly :) I'm a bit confused on what you're describing in the edit, but all the pre-edit is what I meant to describe. When you have several tabs open, having plenty of preview tabs around can be cumbersome and confusing. Having one preview for all files would be neat, as it would display the preview of the matching selected file tab.

Technically I was thinking of opening previews in a tab (or pane, such as the git pane) not linked to any file, a neutral place where all the previews get dynamically loaded depending on the selected tab, which would avoid making Atom closing/opening a preview tab. Though I have no idea if it's feasible.

**Comment by eidolies** [comment]
Ah, I see where it's confusing at first: I'm misusing the terms pane and tab. Oops. Sorry! I fixed my original post.
